language: python

python:
    - "2.7"
    - "3.5"

install:
  - sudo apt-get update
  # Install the dependencies and the package:
  - pip install -r requirements.txt
  - python setup.py install
  # Now get set up to run jupyter notebooks:
  - sudo apt-get install texlive-latex-recommended
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install chktex
  - sudo apt-get install dvipng
  - sudo apt-get install pandoc
  - pip install --upgrade jupyter
  - pip install nbconvert
  # Finally get set up to build the docs

script:
  # Run the unit tests:
  #   - nosetests
  # Run the demo notebook, to make main.html:
  - jupyter nbconvert --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=600 --to html --execute desc_note/kaggle-run.ipynb
  #   - jupyter nbconvert --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=600 --execute desc_note/main.ipynb --to notebook ; cp desc_note/main.nbconvert.ipynb .
  #   - jupyter nbconvert --TagRemovePreprocessor.remove_cell_tags='["hideme"]' --TagRemovePreprocessor.remove_input_tags='["hidein"]' desc_note/main.nbconvert.ipynb  ; cp desc_note/main.nbconvert.html .

  # Finally, if it's the master branch be
  # ing updated, force-push the
  # notebook html pages to an otherwise empty "html" branch:
  #     if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  # after_success: |
  #     if [ -n "$GITHUB_API_KEY" ]; then
  #         git checkout --orphan html
  #         git rm -rf .
  #         git add -f main.html
  #         git -c user.name='travis' -c user.email='travis' commit -m init
  #         git push -q -f https://aimalz:$GITHUB_API_KEY@github.com/aimalz/proclam html
  #     fi
